### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by ejokeeffe** [UCL-ShippingGroup/pyrate#31]
The recent change to how status was generated is causing inheriting projects to fail. Should this change have been a major (non backwards compatible) change?

**Comment by willu47** [comment]
Hi Eoin; Sorry to hear that.  What error message are you getting?  The change should have been backwards compatible.

**Comment by ejokeeffe** [comment]
The metrics table checks if status is zero and if it is then attempts to insert the new metrics. It was getting a unique name violation. Can't quite figure out how it's happening, but pyrate 1.4 works fine. It's fine, I've just reference the commit from last week before you've made the most recent change for pyrate and that seems to work. I should have been doing this anyway - rather than just referencing pyrate. 

If you want to recreate, then download the most recent exactverify release and run the tests.
