### ISSUE TITLE
Unable to extract zip files with compression type 9 (deflate64)

### ISSUE THREAD

**Issue by vprakash-ucl** [UCL-ShippingGroup/pyrate#33]
Zip files that use compression type 9 (deflate64) cannot be extracted as part of aisparser. Returns:

```
Unable to extract zip file ...: compression type 9 (deflate64)
```

Support for compression type 9 may never be added to the python zipfile library: 
- [http://stackoverflow.com/a/12809847](http://stackoverflow.com/a/12809847)
- [https://bugs.python.org/issue14313](https://bugs.python.org/issue14313)

7zip on Ubuntu is able to extract these archives, so a solution may be to call the command line function `7z` from python to do the extraction to a temporary folder to parse (and purge temporary files after parsing).

**Comment by ejokeeffe** [comment]
can you ask them to rezip? They used the python compatible zip format when doing the work for product one? That was only about 4 weeks ago

**Comment by vprakash-ucl** [comment]
Yes, I will ask them to do that from now on. Extracting locally prior to running aisparser is not that onerous, and, given that there is no direct solution, perhaps we just need to mention in the documentation that compression type 9 won't work automatically for the time being---or just leave the issue open.

**Comment by willu47** [comment]
Not a pyrate issue _per se_, as specific to the AIS data.
