### ISSUE TITLE
CLI: Commands need to be typed in same directory as config file

### ISSUE THREAD

**Issue by willu47** [UCL-ShippingGroup/pyrate#8]
At the moment, the config file is required to be in the same folder as the that in which the command line interface is used.

For example typing `pyrate aisdb` in my user directory results in an error `pyrate: error: invalid choice: 'aisdb' (choose from 'list')`, while `pyrate list` turns up empty.

```
0 repositories:
0 algorithms:
```

If I navigate to my pyrate repository folder, then the commands work as you would imagine.

**Comment by ejokeeffe** [comment]
also, the name of the config file has to be aistool.conf - it would be good if you could pass the the name

**Comment by willu47** [comment]
Yep, I've been thinking about this.  There could be one master config file, which is then updated through various commands passed to the cli, or overwritten with a user supplied config file.  This config would be stored in a system defined location upon install, and the cli would give access to it.

We can add files to the install file system using the `[files]` entry in `setup.cfg` and these files can be accessed programmatically using the following code placed in the `__init__.py` of the pyrate module:

``` python
from pkg_resources import resource_string, \
                          resource_filename, \
                          get_distribution

def get_resource_contents(path):
    """ Returns the absolute path associated with the file

    Arguments
    =========
    path : str
        The expected file path

    Returns
    =======
    path : str
        The contents of the file
    """
    return resource_string(__name__, path)


def get_resource_filename(path):
    """ Returns the absolute path associated with the file

    Arguments
    =========
    path : str
        The expected file path

    Returns
    =======
    path : str
        The absolute file path
    """
    return resource_filename(__name__, path)
```

**Comment by willu47** [comment]
This issue is still outstanding - I'm not happy with my 'solutions' posted previously.  

I think it makes sense to require that the config file is in the root folder of a particular analysis, and that a separate folder is required for each configuration used, even if the repository used to store the AIS data (e.g. postgres) is accessed remotely.  For example:

```
analysis_folder 
    results_folder
    input_data_folder
        - ais_file.csv
        - another_ais_file.csv
        - more_ais_data.zip
    - log_file.log
    - config_file.conf

another_folder_for_analysis
    input_data_folder
    add_ons
        algorithms
        - my_algo_for_pyrate.py
    - config_file.conf
    - log_file.log
    - some_analysis_code.py
```

Overall, this would make it considerably easier to code the command line interface (`cli.py`).  I'd also suggest using an argument in the CLI to allow the default config file name to be defined, although this would need to be defined each time using a flag (such as `-config custom_config.conf`, and would be handy for debugging).
